server:
  port: 8081
  servlet:
    context-path: /

spring:
  data:
    redis:
      repositories:
        enabled: false
  datasource:
    url: jdbc:mysql://81.69.225.235:3306/db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ajt
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
      maximum-pool-size: 10
      minimum-idle: 3
  jpa:
    show-sql: false
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true
    hibernate:
      ddl-auto: update
  redis:
    host: 81.69.225.235
    port: 6379



# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 36000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: 36000
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false

sms:
  account: 'C22277688'
  password: '2aa817ef8e82851ad7d90bf6edf228b4'
  content: '您的验证码是：1254。请不要把验证码泄露给其他人。'

oss:
  endpoint: 'http://oss-cn-shanghai.aliyuncs.com'
  accessKeyId: 'LTAI5tBAWxg5mH5qAKzxbxc9'
  accessKeySecret: 'ZQrtUsNYYwJlgeIsyGis2F6mp1Tpyd'
  bucketName: 'javaee-xjj'

